#!/usr/bin/env node
// Regenerates src/dashboard/vendor.ts from pinned htmx + Alpine releases.
// Run manually when bumping versions; the output is checked in so the
// build has no network dependency. Bump each URL and SHA-256 together.
import { createHash } from 'node:crypto';
import { writeFileSync } from 'node:fs';

import { PINS } from './vendor-pins.mjs';

let out =
  '// GENERATED by scripts/vendor-ui.mjs - do not edit by hand.\n' +
  '// htmx 2.0.4 (BSD-2) + Alpine.js 3.14.9 (MIT), inlined so the dashboard\n' +
  '// works offline and ships inside the single-file npm package.\n';
for (const { name, url, sha256 } of PINS) {
  if (!name || !url || !sha256) throw new Error('invalid vendor pin');
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url}: ${res.status}`);
  const js = await res.text();
  const actual = createHash('sha256').update(js, 'utf8').digest('hex');
  if (actual !== sha256) throw new Error(`${name}: SHA-256 mismatch`);
  out += `\nexport const ${name} = ${JSON.stringify(js)};\n`;
}
writeFileSync('src/dashboard/vendor.ts', out);
console.log('wrote src/dashboard/vendor.ts');
