import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { spawnSync } from 'node:child_process';

export const LAUNCHD_LABEL = 'com.imgtokenx.proxy';
export const MCP_SERVER_NAME = 'imgtokenx-recover';

export interface InstallPlan {
  home: string;
  repoRoot: string;
  nodePath: string;
  cliPath: string;
  port: number;
  baseUrl: string;
  imgtokenxDir: string;
  envPath: string;
  zshrcPath: string;
  launchAgentPath: string;
  outLog: string;
  errLog: string;
  plist: string;
  envSh: string;
  zshrcBlock: string;
  mcpCommands: string[];
  opencodeMcp: Record<string, unknown>;
}

interface BuildPlanOptions {
  home?: string;
  repoRoot?: string;
  nodePath?: string;
  port?: number;
}

export interface InstallOptions extends BuildPlanOptions {
  dryRun?: boolean;
  skipMcp?: boolean;
}

export interface InstallResult {
  plan: InstallPlan;
  actions: string[];
}

export type DoctorStatus = 'pass' | 'fail' | 'warn';

export interface DoctorCheck {
  name: string;
  status: DoctorStatus;
  detail: string;
}

export interface DoctorResult {
  plan: InstallPlan;
  checks: DoctorCheck[];
}

interface DoctorDeps {
  fetch?: typeof fetch;
  spawnSync?: typeof spawnSync;
}

function q(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

function xml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function shDouble(s: string): string {
  return s.replace(/["\\$`]/g, '\\$&');
}

function timestamp(): string {
  return new Date().toISOString().replace(/[:.]/g, '-');
}

function run(cmd: string, args: string[], actions: string[], opts: { ignoreFailure?: boolean } = {}): void {
  actions.push([cmd, ...args].map(q).join(' '));
  const r = spawnSync(cmd, args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
  if (r.status !== 0 && !opts.ignoreFailure) {
    throw new Error(`${cmd} ${args.join(' ')} failed: ${(r.stderr || r.stdout || '').trim()}`);
  }
}

export function renderLaunchAgentPlist(plan: Pick<InstallPlan, 'nodePath' | 'cliPath' | 'port' | 'outLog' | 'errLog' | 'repoRoot'>): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LAUNCHD_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${xml(plan.nodePath)}</string>
    <string>${xml(plan.cliPath)}</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${xml(plan.repoRoot)}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>HOST</key>
    <string>127.0.0.1</string>
    <key>PORT</key>
    <string>${plan.port}</string>
  </dict>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${xml(plan.outLog)}</string>
  <key>StandardErrorPath</key>
  <string>${xml(plan.errLog)}</string>
</dict>
</plist>
`;
}

export function renderShellEnv(plan: Pick<InstallPlan, 'nodePath' | 'cliPath' | 'baseUrl' | 'port'>): string {
  return `# Generated by imgtokenx install. Source from ~/.zshrc.
export IMGTOKENX_BASE_URL="\${IMGTOKENX_BASE_URL:-${shDouble(plan.baseUrl)}}"
export IMGTOKENX_PORT="\${IMGTOKENX_PORT:-${plan.port}}"
export IMGTOKENX_NODE="\${IMGTOKENX_NODE:-${shDouble(plan.nodePath)}}"
export IMGTOKENX_CLI="\${IMGTOKENX_CLI:-${shDouble(plan.cliPath)}}"

imgtokenx_health() {
  command curl -fsS "$IMGTOKENX_BASE_URL/healthz" >/dev/null 2>&1
}

imgtokenx_ensure_proxy() {
  imgtokenx_health && return 0
  if command -v launchctl >/dev/null 2>&1; then
    command launchctl kickstart -k "gui/$(id -u)/${LAUNCHD_LABEL}" >/dev/null 2>&1 || true
    sleep 0.3
    imgtokenx_health && return 0
  fi
  mkdir -p "$HOME/.imgtokenx"
  HOST=127.0.0.1 PORT="$IMGTOKENX_PORT" nohup "$IMGTOKENX_NODE" "$IMGTOKENX_CLI" >> "$HOME/.imgtokenx/proxy.out.log" 2>> "$HOME/.imgtokenx/proxy.err.log" &
  sleep 0.5
  imgtokenx_health
}

claude() {
  if [ "\${IMGTOKENX_DISABLE:-}" = "1" ]; then command claude "$@"; return $?; fi
  imgtokenx_ensure_proxy || echo "[imgtokenx] warning: proxy health check failed; running claude anyway" >&2
  ANTHROPIC_BASE_URL="$IMGTOKENX_BASE_URL" command claude "$@"
}

codex() {
  if [ "\${IMGTOKENX_DISABLE:-}" = "1" ]; then command codex "$@"; return $?; fi
  imgtokenx_ensure_proxy || echo "[imgtokenx] warning: proxy health check failed; running codex anyway" >&2
  OPENAI_BASE_URL="$IMGTOKENX_BASE_URL/v1" command codex "$@"
}

opencode() {
  if [ "\${IMGTOKENX_DISABLE:-}" = "1" ]; then command opencode "$@"; return $?; fi
  imgtokenx_ensure_proxy || echo "[imgtokenx] warning: proxy health check failed; running opencode anyway" >&2
  ANTHROPIC_BASE_URL="$IMGTOKENX_BASE_URL/anthropic" OPENAI_BASE_URL="$IMGTOKENX_BASE_URL/openai" command opencode "$@"
}
`;
}

function zshrcBlock(envPath: string): string {
  return [
    '# >>> imgtokenx auto-start >>>',
    `[ -r ${q(envPath)} ] && . ${q(envPath)}`,
    '# <<< imgtokenx auto-start <<<',
  ].join('\n');
}

export function applyZshrcInstall(current: string, block: string): string {
  if (current.includes(block)) return current;
  const withoutOld = applyZshrcUninstall(current);
  return `${withoutOld.replace(/\s*$/, '')}\n\n${block}\n`;
}

export function applyZshrcUninstall(current: string): string {
  return current
    .replace(/\n?# >>> imgtokenx auto-start >>>\n[\s\S]*?\n# <<< imgtokenx auto-start <<<\n?/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .replace(/^\n+/, '')
    .replace(/\n{2,}$/, '\n');
}

export function buildInstallPlan(opts: BuildPlanOptions = {}): InstallPlan {
  const home = opts.home ?? os.homedir();
  const repoRoot = opts.repoRoot ?? process.cwd();
  const nodePath = opts.nodePath ?? process.execPath;
  const cliPath = path.join(repoRoot, 'bin', 'cli.js');
  const port = opts.port ?? 47821;
  const imgtokenxDir = path.join(home, '.imgtokenx');
  const launchAgentPath = path.join(home, 'Library', 'LaunchAgents', `${LAUNCHD_LABEL}.plist`);
  const plan = {
    home,
    repoRoot,
    nodePath,
    cliPath,
    port,
    baseUrl: `http://127.0.0.1:${port}`,
    imgtokenxDir,
    envPath: path.join(imgtokenxDir, 'env.sh'),
    zshrcPath: path.join(home, '.zshrc'),
    launchAgentPath,
    outLog: path.join(imgtokenxDir, 'proxy.out.log'),
    errLog: path.join(imgtokenxDir, 'proxy.err.log'),
  } as InstallPlan;
  plan.plist = renderLaunchAgentPlist(plan);
  plan.envSh = renderShellEnv(plan);
  plan.zshrcBlock = zshrcBlock(plan.envPath);
  plan.mcpCommands = [
    `claude mcp add --scope user ${MCP_SERVER_NAME} -- ${q(nodePath)} ${q(cliPath)} mcp`,
    `codex mcp add ${MCP_SERVER_NAME} -- ${q(nodePath)} ${q(cliPath)} mcp`,
  ];
  plan.opencodeMcp = {
    enabled: true,
    type: 'local',
    command: [nodePath, cliPath, 'mcp'],
  };
  return plan;
}

function writeIfChanged(file: string, content: string, actions: string[], mode?: number): void {
  if (fs.existsSync(file) && fs.readFileSync(file, 'utf8') === content) return;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content, { mode });
  actions.push(`write ${file}`);
}

function backup(file: string, actions: string[]): void {
  if (!fs.existsSync(file)) return;
  const to = `${file}.bak.${timestamp()}`;
  fs.copyFileSync(file, to);
  actions.push(`backup ${file} -> ${to}`);
}

function updateZshrc(plan: InstallPlan, actions: string[], installing: boolean): void {
  const cur = fs.existsSync(plan.zshrcPath) ? fs.readFileSync(plan.zshrcPath, 'utf8') : '';
  const next = installing ? applyZshrcInstall(cur, plan.zshrcBlock) : applyZshrcUninstall(cur);
  if (next === cur) return;
  backup(plan.zshrcPath, actions);
  fs.writeFileSync(plan.zshrcPath, next);
  actions.push(`${installing ? 'update' : 'clean'} ${plan.zshrcPath}`);
}

function updateOpencodeConfig(plan: InstallPlan, actions: string[], installing: boolean): void {
  const file = path.join(plan.home, '.config', 'opencode', 'opencode.json');
  let cfg: Record<string, unknown> = {};
  if (fs.existsSync(file)) cfg = JSON.parse(fs.readFileSync(file, 'utf8')) as Record<string, unknown>;
  const mcp = (cfg.mcp && typeof cfg.mcp === 'object' && !Array.isArray(cfg.mcp))
    ? { ...(cfg.mcp as Record<string, unknown>) }
    : {};
  if (installing) mcp[MCP_SERVER_NAME] = plan.opencodeMcp;
  else delete mcp[MCP_SERVER_NAME];
  cfg.mcp = mcp;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  backup(file, actions);
  fs.writeFileSync(file, JSON.stringify(cfg, null, 2) + '\n');
  actions.push(`${installing ? 'upsert' : 'remove'} ${MCP_SERVER_NAME} in ${file}`);
}

function printDryRun(plan: InstallPlan, installing: boolean, skipMcp: boolean): void {
  const title = installing ? 'install' : 'uninstall';
  console.log(`[imgtokenx ${title}] dry run; no files or live config changed`);
  console.log(`launchd plist: ${plan.launchAgentPath}`);
  console.log(`shell env:     ${plan.envPath}`);
  console.log(`zshrc block:\n${plan.zshrcBlock}`);
  if (installing) {
    console.log(`\nlaunchd plist preview:\n${plan.plist}`);
    console.log(`env.sh preview:\n${plan.envSh}`);
  }
  if (!skipMcp) {
    console.log('\nMCP registration:');
    for (const cmd of plan.mcpCommands) console.log(`  ${cmd}`);
    console.log(`  opencode config mcp.${MCP_SERVER_NAME}: ${JSON.stringify(plan.opencodeMcp)}`);
  }
}

export function runInstall(opts: InstallOptions = {}): InstallResult {
  const plan = buildInstallPlan(opts);
  const actions: string[] = [];
  if (opts.dryRun) {
    printDryRun(plan, true, Boolean(opts.skipMcp));
    return { plan, actions };
  }
  writeIfChanged(plan.launchAgentPath, plan.plist, actions, 0o644);
  writeIfChanged(plan.envPath, plan.envSh, actions, 0o644);
  updateZshrc(plan, actions, true);
  const domain = `gui/${process.getuid?.() ?? os.userInfo().uid}`;
  run('launchctl', ['bootout', domain, plan.launchAgentPath], actions, { ignoreFailure: true });
  run('launchctl', ['bootstrap', domain, plan.launchAgentPath], actions);
  run('launchctl', ['enable', `${domain}/${LAUNCHD_LABEL}`], actions, { ignoreFailure: true });
  run('launchctl', ['kickstart', '-k', `${domain}/${LAUNCHD_LABEL}`], actions, { ignoreFailure: true });
  if (!opts.skipMcp) {
    run('claude', ['mcp', 'remove', '--scope', 'user', MCP_SERVER_NAME], actions, { ignoreFailure: true });
    run('claude', ['mcp', 'add', '--scope', 'user', MCP_SERVER_NAME, '--', plan.nodePath, plan.cliPath, 'mcp'], actions, { ignoreFailure: true });
    run('codex', ['mcp', 'remove', MCP_SERVER_NAME], actions, { ignoreFailure: true });
    run('codex', ['mcp', 'add', MCP_SERVER_NAME, '--', plan.nodePath, plan.cliPath, 'mcp'], actions, { ignoreFailure: true });
    updateOpencodeConfig(plan, actions, true);
  }
  return { plan, actions };
}

export function runUninstall(opts: InstallOptions = {}): InstallResult {
  const plan = buildInstallPlan(opts);
  const actions: string[] = [];
  if (opts.dryRun) {
    printDryRun(plan, false, Boolean(opts.skipMcp));
    return { plan, actions };
  }
  const domain = `gui/${process.getuid?.() ?? os.userInfo().uid}`;
  run('launchctl', ['bootout', domain, plan.launchAgentPath], actions, { ignoreFailure: true });
  if (fs.existsSync(plan.launchAgentPath)) {
    fs.unlinkSync(plan.launchAgentPath);
    actions.push(`remove ${plan.launchAgentPath}`);
  }
  if (fs.existsSync(plan.envPath)) {
    fs.unlinkSync(plan.envPath);
    actions.push(`remove ${plan.envPath}`);
  }
  updateZshrc(plan, actions, false);
  if (!opts.skipMcp) {
    run('claude', ['mcp', 'remove', '--scope', 'user', MCP_SERVER_NAME], actions, { ignoreFailure: true });
    run('codex', ['mcp', 'remove', MCP_SERVER_NAME], actions, { ignoreFailure: true });
    updateOpencodeConfig(plan, actions, false);
  }
  return { plan, actions };
}

function status(name: string, ok: boolean, pass: string, fail: string): DoctorCheck {
  return { name, status: ok ? 'pass' : 'fail', detail: ok ? pass : fail };
}

function spawnCheck(name: string, cmd: string, args: string[], deps: DoctorDeps): DoctorCheck {
  const sp = deps.spawnSync ?? spawnSync;
  const r = sp(cmd, args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
  if (r.error && (r.error as NodeJS.ErrnoException).code === 'ENOENT') {
    return { name, status: 'warn', detail: `${cmd} not found` };
  }
  if (r.status === 0) return { name, status: 'pass', detail: `${cmd} ${args.join(' ')}` };
  const msg = String(r.stderr || r.stdout || '').trim();
  return { name, status: 'fail', detail: msg || `${cmd} ${args.join(' ')} exited ${r.status}` };
}

async function healthCheck(plan: InstallPlan, deps: DoctorDeps): Promise<DoctorCheck> {
  const f = deps.fetch ?? fetch;
  const ac = new AbortController();
  const timer = setTimeout(() => ac.abort(), 1500);
  try {
    const res = await f(`${plan.baseUrl}/healthz`, { signal: ac.signal });
    return status('healthz', res.ok, `${plan.baseUrl}/healthz`, `HTTP ${res.status} from ${plan.baseUrl}/healthz`);
  } catch (err) {
    return { name: 'healthz', status: 'fail', detail: (err as Error).message };
  } finally {
    clearTimeout(timer);
  }
}

export async function runDoctor(opts: InstallOptions = {}, deps: DoctorDeps = {}): Promise<DoctorResult> {
  const plan = buildInstallPlan(opts);
  const checks: DoctorCheck[] = [];
  checks.push(status('launchd plist', fs.existsSync(plan.launchAgentPath), plan.launchAgentPath, `missing ${plan.launchAgentPath}`));
  checks.push(status('shell env', fs.existsSync(plan.envPath), plan.envPath, `missing ${plan.envPath}`));
  const zshrc = fs.existsSync(plan.zshrcPath) ? fs.readFileSync(plan.zshrcPath, 'utf8') : '';
  checks.push(status('zshrc source block', zshrc.includes(plan.zshrcBlock), plan.zshrcPath, `missing imgtokenx source block in ${plan.zshrcPath}`));
  checks.push(await healthCheck(plan, deps));

  const domain = `gui/${process.getuid?.() ?? os.userInfo().uid}`;
  checks.push(spawnCheck('launchd service', 'launchctl', ['print', `${domain}/${LAUNCHD_LABEL}`], deps));
  if (!opts.skipMcp) {
    checks.push(spawnCheck('Claude MCP', 'claude', ['mcp', 'get', MCP_SERVER_NAME], deps));
    checks.push(spawnCheck('Codex MCP', 'codex', ['mcp', 'get', MCP_SERVER_NAME], deps));
    const cfgPath = path.join(plan.home, '.config', 'opencode', 'opencode.json');
    let opencodeOk = false;
    if (fs.existsSync(cfgPath)) {
      try {
        const cfg = JSON.parse(fs.readFileSync(cfgPath, 'utf8')) as { mcp?: Record<string, unknown> };
        const entry = cfg.mcp?.[MCP_SERVER_NAME] as { command?: unknown } | undefined;
        opencodeOk = Array.isArray(entry?.command)
          && entry.command[0] === plan.nodePath
          && entry.command[1] === plan.cliPath
          && entry.command[2] === 'mcp';
      } catch {
        opencodeOk = false;
      }
    }
    checks.push(status('OpenCode MCP', opencodeOk, cfgPath, `missing ${MCP_SERVER_NAME} in ${cfgPath}`));
  }
  return { plan, checks };
}

export function doctorExitCode(result: DoctorResult): number {
  return result.checks.some((c) => c.status === 'fail') ? 1 : 0;
}

export function formatDoctor(result: DoctorResult): string {
  const mark = { pass: 'PASS', fail: 'FAIL', warn: 'WARN' } satisfies Record<DoctorStatus, string>;
  return result.checks.map((c) => `${mark[c.status]} ${c.name}: ${c.detail}`).join('\n') + '\n';
}

export function parseInstallArgs(argv: string[]): InstallOptions {
  const opts: InstallOptions = {};
  for (const a of argv) {
    if (a === '--dry-run') opts.dryRun = true;
    else if (a === '--skip-mcp') opts.skipMcp = true;
    else if (a.startsWith('--port=')) {
      const port = Number(a.slice('--port='.length));
      if (!Number.isInteger(port) || port < 1 || port > 65535) {
        throw new Error(`invalid --port value: ${a.slice('--port='.length)}`);
      }
      opts.port = port;
    }
    else if (a === '-h' || a === '--help') {
      console.log('Usage: imgtokenx install|uninstall|doctor [--dry-run] [--skip-mcp] [--port=47821]');
      process.exit(0);
    } else {
      throw new Error(`unknown install option: ${a}`);
    }
  }
  return opts;
}
