import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { spawnSync } from 'node:child_process';
import { readFileOrNull, writeFileAtomic } from './core/fs-atomic.js';

export const LAUNCHD_LABEL = 'com.imgtokenx.proxy';
export const MCP_SERVER_NAME = 'imgtokenx-recover';

export interface InstallPlan {
  home: string;
  repoRoot: string;
  nodePath: string;
  cliPath: string;
  port: number;
  baseUrl: string;
  imgtokenxDir: string;
  envPath: string;
  zshrcPath: string;
  launchAgentPath: string;
  outLog: string;
  errLog: string;
  plist: string;
  envSh: string;
  zshrcBlock: string;
  mcpCommands: string[];
  opencodeMcp: Record<string, unknown>;
}

interface BuildPlanOptions {
  home?: string;
  repoRoot?: string;
  nodePath?: string;
  port?: number;
}

export interface InstallOptions extends BuildPlanOptions {
  dryRun?: boolean;
  skipMcp?: boolean;
  /** Process runner override for deterministic embedders/tests. */
  spawnSync?: (command: string, args: string[], options: {
    encoding: 'utf8';
    stdio: ['ignore', 'pipe', 'pipe'];
  }) => { status: number | null; error?: Error; stderr?: string | Buffer | null; stdout?: string | Buffer | null };
}

export interface InstallResult {
  plan: InstallPlan;
  actions: string[];
}

export type DoctorStatus = 'pass' | 'fail' | 'warn';

export interface DoctorCheck {
  name: string;
  status: DoctorStatus;
  detail: string;
}

export interface DoctorResult {
  plan: InstallPlan;
  checks: DoctorCheck[];
}

interface DoctorDeps {
  fetch?: typeof fetch;
  spawnSync?: typeof spawnSync;
}

/** Internal bookkeeping record: a description surfaced in
 *  InstallResult.actions, plus a `revert` closure that puts the system
 *  back to its pre-install state. Reversed-iterated on failure. */
interface UndoStep {
  log: string;
  revert: () => void;
}

function q(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

function xml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function shDouble(s: string): string {
  return s.replace(/["\\$`]/g, '\\$&');
}

function timestamp(): string {
  return new Date().toISOString().replace(/[:.]/g, '-');
}

export function renderLaunchAgentPlist(plan: Pick<InstallPlan, 'nodePath' | 'cliPath' | 'port' | 'outLog' | 'errLog' | 'repoRoot'>): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LAUNCHD_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${xml(plan.nodePath)}</string>
    <string>${xml(plan.cliPath)}</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${xml(plan.repoRoot)}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>HOST</key>
    <string>127.0.0.1</string>
    <key>PORT</key>
    <string>${plan.port}</string>
  </dict>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${xml(plan.outLog)}</string>
  <key>StandardErrorPath</key>
  <string>${xml(plan.errLog)}</string>
</dict>
</plist>
`;
}

export function renderShellEnv(plan: Pick<InstallPlan, 'nodePath' | 'cliPath' | 'baseUrl' | 'port'>): string {
  return `# Generated by imgtokenx install. Source from ~/.zshrc.
export IMGTOKENX_BASE_URL="\${IMGTOKENX_BASE_URL:-${shDouble(plan.baseUrl)}}"
export IMGTOKENX_PORT="\${IMGTOKENX_PORT:-${plan.port}}"
export IMGTOKENX_NODE="\${IMGTOKENX_NODE:-${shDouble(plan.nodePath)}}"
export IMGTOKENX_CLI="\${IMGTOKENX_CLI:-${shDouble(plan.cliPath)}}"

imgtokenx_disabled() {
  [ "\${IMGTOKENX_DISABLE:-}" = "1" ] || [ -e "$HOME/.imgtokenx/disabled" ]
}

imgtokenx_health() {
  command curl -fsS "$IMGTOKENX_BASE_URL/healthz" >/dev/null 2>&1
}

imgtokenx_ensure_proxy() {
  imgtokenx_health && return 0
  if command -v launchctl >/dev/null 2>&1; then
    command launchctl kickstart -k "gui/$(id -u)/${LAUNCHD_LABEL}" >/dev/null 2>&1 || true
    sleep 0.3
    imgtokenx_health && return 0
  fi
  mkdir -p "$HOME/.imgtokenx"
  HOST=127.0.0.1 PORT="$IMGTOKENX_PORT" nohup "$IMGTOKENX_NODE" "$IMGTOKENX_CLI" >> "$HOME/.imgtokenx/proxy.out.log" 2>> "$HOME/.imgtokenx/proxy.err.log" &
  sleep 0.5
  imgtokenx_health
}

claude() {
  if imgtokenx_disabled; then command claude "$@"; return $?; fi
  if ! imgtokenx_ensure_proxy; then echo "[imgtokenx] proxy unavailable; bypassing it" >&2; command claude "$@"; return $?; fi
  ANTHROPIC_BASE_URL="$IMGTOKENX_BASE_URL" command claude "$@"
}

codex() {
  if imgtokenx_disabled; then command codex "$@"; return $?; fi
  if ! imgtokenx_ensure_proxy; then echo "[imgtokenx] proxy unavailable; bypassing it" >&2; command codex "$@"; return $?; fi
  OPENAI_BASE_URL="$IMGTOKENX_BASE_URL/v1" command codex "$@"
}

opencode() {
  if imgtokenx_disabled; then command opencode "$@"; return $?; fi
  if ! imgtokenx_ensure_proxy; then echo "[imgtokenx] proxy unavailable; bypassing it" >&2; command opencode "$@"; return $?; fi
  ANTHROPIC_BASE_URL="$IMGTOKENX_BASE_URL/anthropic" OPENAI_BASE_URL="$IMGTOKENX_BASE_URL/openai" command opencode "$@"
}
`;
}

function zshrcBlock(envPath: string): string {
  return [
    '# >>> imgtokenx auto-start >>>',
    `[ -r ${q(envPath)} ] && . ${q(envPath)}`,
    '# <<< imgtokenx auto-start <<<',
  ].join('\n');
}

export function applyZshrcInstall(current: string, block: string): string {
  if (current.includes(block)) return current;
  const withoutOld = applyZshrcUninstall(current);
  return `${withoutOld.replace(/\s*$/, '')}\n\n${block}\n`;
}

export function applyZshrcUninstall(current: string): string {
  return current
    .replace(/\n?# >>> imgtokenx auto-start >>>\n[\s\S]*?\n# <<< imgtokenx auto-start <<<\n?/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .replace(/^\n+/, '')
    .replace(/\n{2,}$/, '\n');
}

export function buildInstallPlan(opts: BuildPlanOptions = {}): InstallPlan {
  const home = opts.home ?? os.homedir();
  const repoRoot = opts.repoRoot ?? process.cwd();
  const nodePath = opts.nodePath ?? process.execPath;
  const cliPath = path.join(repoRoot, 'bin', 'cli.js');
  const port = opts.port ?? 47821;
  const imgtokenxDir = path.join(home, '.imgtokenx');
  const launchAgentPath = path.join(home, 'Library', 'LaunchAgents', `${LAUNCHD_LABEL}.plist`);
  const plan = {
    home,
    repoRoot,
    nodePath,
    cliPath,
    port,
    baseUrl: `http://127.0.0.1:${port}`,
    imgtokenxDir,
    envPath: path.join(imgtokenxDir, 'env.sh'),
    zshrcPath: path.join(home, '.zshrc'),
    launchAgentPath,
    outLog: path.join(imgtokenxDir, 'proxy.out.log'),
    errLog: path.join(imgtokenxDir, 'proxy.err.log'),
  } as InstallPlan;
  plan.plist = renderLaunchAgentPlist(plan);
  plan.envSh = renderShellEnv(plan);
  plan.zshrcBlock = zshrcBlock(plan.envPath);
  plan.mcpCommands = [
    `claude mcp add --scope user ${MCP_SERVER_NAME} -- ${q(nodePath)} ${q(cliPath)} mcp`,
    `codex mcp add ${MCP_SERVER_NAME} -- ${q(nodePath)} ${q(cliPath)} mcp`,
  ];
  plan.opencodeMcp = {
    enabled: true,
    type: 'local',
    command: [nodePath, cliPath, 'mcp'],
  };
  return plan;
}

/** Write `content` to `file` atomically. Records an UndoStep so a partial
 *  install failure can roll back. If `file` already existed and had a
 *  different byte sequence, the prior bytes go to `<file>.bak.<ts>` so
 *  rollback restores them byte-for-byte. */
function writeWithUndo(
  file: string,
  content: string,
  undo: UndoStep[],
  mode: number,
): void {
  const prior = readFileOrNull(file);
  const exists = prior !== null;
  const same = exists && prior!.toString('utf8') === content;
  if (same) {
    undo.push({
      log: `no-op ${file} (content unchanged)`,
      revert: () => { /* no-op */ },
    });
    return;
  }
  writeFileAtomic(file, content, { mode });
  undo.push({
    log: `write ${file}`,
    revert: () => {
      if (!exists) {
        try { fs.rmSync(file, { force: true }); } catch { /* best-effort */ }
        return;
      }
      // Restore prior contents atomically. If the prior content was
      // already captured into a .bak.<ts> by `backup()` above, we let
      // that helper own the restore; for new files written here, we
      // rewrite the original bytes.
      try {
        writeFileAtomic(file, prior!, { mode });
      } catch {
        /* best-effort */
      }
    },
  });
}

/** Snapshot a file to `.bak.<ts>` BEFORE overwriting it. Used by updateZshrc
 *  and updateOpencodeConfig since those replace existing user config and
 *  need a recoverable rollback. */
function backup(file: string, undo: UndoStep[]): string | undefined {
  const prior = readFileOrNull(file);
  if (prior === null) {
    undo.push({
      log: `no-op backup ${file} (file absent)`,
      revert: () => { /* no-op */ },
    });
    return undefined;
  }
  const bakPath = `${file}.bak.${timestamp()}`;
  try {
    writeFileAtomic(bakPath, prior, { mode: 0o600 });
    undo.push({
      log: `backup ${file} -> ${bakPath}`,
      revert: () => {
        try {
          writeFileAtomic(file, prior!, { mode: 0o600 });
          fs.rmSync(bakPath, { force: true });
        } catch {
          /* best-effort */
        }
      },
    });
    return bakPath;
  } catch (err) {
    throw new Error(`could not back up ${file}: ${(err as Error).message}`);
  }
}

function updateZshrc(plan: InstallPlan, undo: UndoStep[], installing: boolean): void {
  const cur = fs.existsSync(plan.zshrcPath) ? fs.readFileSync(plan.zshrcPath, 'utf8') : '';
  const next = installing ? applyZshrcInstall(cur, plan.zshrcBlock) : applyZshrcUninstall(cur);
  if (next === cur) {
    undo.push({
      log: `no-op ${installing ? 'update' : 'clean'} ${plan.zshrcPath} (unchanged)`,
      revert: () => { /* no-op */ },
    });
    return;
  }
  // Take a backup; on rollback, restore via the backup's revert closure.
  backup(plan.zshrcPath, undo);
  writeFileAtomic(plan.zshrcPath, next, { mode: 0o644 });
  undo.push({
    log: `${installing ? 'update' : 'clean'} ${plan.zshrcPath}`,
    revert: () => {
      // Restoration is owned by the backup step's revert closure; the
      // forward-step here is just to delete any newly-written block if the
      // user wants a sub-rollback (the reverse-order caller will hit the
      // backup.revert first which restores the original bytes).
    },
  });
}

function updateOpencodeConfig(plan: InstallPlan, undo: UndoStep[], installing: boolean): void {
  const file = path.join(plan.home, '.config', 'opencode', 'opencode.json');
  let cfg: Record<string, unknown> = {};
  if (fs.existsSync(file)) cfg = JSON.parse(fs.readFileSync(file, 'utf8')) as Record<string, unknown>;
  const mcp = (cfg.mcp && typeof cfg.mcp === 'object' && !Array.isArray(cfg.mcp))
    ? { ...(cfg.mcp as Record<string, unknown>) }
    : {};
  if (installing) mcp[MCP_SERVER_NAME] = plan.opencodeMcp;
  else delete mcp[MCP_SERVER_NAME];
  cfg.mcp = mcp;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  backup(file, undo);
  // opencode.json can hold MCP server env/secrets from other tools — keep it
  // owner-only rather than the writeFileAtomic 0o644 default.
  writeFileAtomic(file, JSON.stringify(cfg, null, 2) + '\n', { mode: 0o600 });
  undo.push({
    log: `${installing ? 'upsert' : 'remove'} ${MCP_SERVER_NAME} in ${file}`,
    revert: () => {
      // Restoration is in the backup step's revert closure.
    },
  });
}

function printDryRun(plan: InstallPlan, installing: boolean, skipMcp: boolean): void {
  const title = installing ? 'install' : 'uninstall';
  console.log(`[imgtokenx ${title}] dry run; no files or live config changed`);
  console.log(`launchd plist: ${plan.launchAgentPath}`);
  console.log(`shell env:     ${plan.envPath}`);
  console.log(`zshrc block:\n${plan.zshrcBlock}`);
  if (installing) {
    console.log(`\nlaunchd plist preview:\n${plan.plist}`);
    console.log(`env.sh preview:\n${plan.envSh}`);
  }
  if (!skipMcp) {
    console.log('\nMCP registration:');
    for (const cmd of plan.mcpCommands) console.log(`  ${cmd}`);
    console.log(`  opencode config mcp.${MCP_SERVER_NAME}: ${JSON.stringify(plan.opencodeMcp)}`);
  }
}

/** Reverse-iterate the undo stack, running each revert in a try/catch so a
 *  failed rollback doesn't leave the operator with an even-brokener install
 *  plus a half-completed one. Always rethrows the ORIGINAL error so the CLI
 *  surfaces the failure cause, not a cobbled-together rollback error. */
function rollback(undo: UndoStep[], originalError: unknown): never {
  for (let i = undo.length - 1; i >= 0; i--) {
    try {
      undo[i]!.revert();
    } catch (err) {
      console.error(
        `[imgtokenx install] rollback step "${undo[i]!.log}" failed: ${(err as Error).message}; continuing rollback`,
      );
    }
  }
  throw originalError;
}

export function runInstall(opts: InstallOptions = {}): InstallResult {
  const plan = buildInstallPlan(opts);
  if (opts.dryRun) {
    const actions: string[] = [];
    printDryRun(plan, true, Boolean(opts.skipMcp));
    return { plan, actions };
  }
  const undo: UndoStep[] = [];
  const actionLog: string[] = [];
  try {
    writeWithUndo(plan.launchAgentPath, plan.plist, undo, 0o644);
    writeWithUndo(plan.envPath, plan.envSh, undo, 0o644);
    updateZshrc(plan, undo, true);
    const domain = `gui/${process.getuid?.() ?? os.userInfo().uid}`;
    const runStep = (cmd: string, args: string[], optsR: { ignoreFailure?: boolean } = {}) => {
      actionLog.push([cmd, ...args].map(q).join(' '));
      const r = (opts.spawnSync ?? spawnSync)(cmd, args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
      // ENOENT = binary missing. Tolerated silently: install/uninstall
      // shouldn't fail loudly for operators without claude / codex / opencode
      // installed locally (audit D20: missing-CLI is benign, --skip-mcp is
      // the explicit opt-out). Real exec failures still throw.
      if (r.error && (r.error as NodeJS.ErrnoException).code === 'ENOENT') return;
      // r.status !== 0 catches BOTH non-zero exit AND spawn errors (EACCES,
      // EPERM, etc.) that leave status = null. The earlier ENOENT branch
      // already silenced missing-binary; all other failures must throw so
      // rollback can run. r.error.message surfaces when the binary itself
      // failed to launch (no stderr/stdout in those cases).
      if (r.status !== 0 && !optsR.ignoreFailure) {
        const detail = ((r.error as Error | undefined)?.message
          ?? (typeof r.stderr === 'string' ? r.stderr : '')
          ?? (typeof r.stdout === 'string' ? r.stdout : '')).trim();
        throw new Error(`${cmd} ${args.join(' ')} failed: ${detail}`);
      }
    };
    runStep('launchctl', ['bootout', domain, plan.launchAgentPath], { ignoreFailure: true });
    runStep('launchctl', ['bootstrap', domain, plan.launchAgentPath], {});
    runStep('launchctl', ['enable', `${domain}/${LAUNCHD_LABEL}`], { ignoreFailure: true });
    runStep('launchctl', ['kickstart', '-k', `${domain}/${LAUNCHD_LABEL}`], { ignoreFailure: true });
    if (!opts.skipMcp) {
      runStep('claude', ['mcp', 'remove', '--scope', 'user', MCP_SERVER_NAME], { ignoreFailure: true });
      runStep('claude', ['mcp', 'add', '--scope', 'user', MCP_SERVER_NAME, '--', plan.nodePath, plan.cliPath, 'mcp']);
      runStep('codex', ['mcp', 'remove', MCP_SERVER_NAME], { ignoreFailure: true });
      runStep('codex', ['mcp', 'add', MCP_SERVER_NAME, '--', plan.nodePath, plan.cliPath, 'mcp']);
      updateOpencodeConfig(plan, undo, true);
    }
  } catch (err) {
    rollback(undo, err);
  }
  // Flatten undo log into the public action list. Each revert's log message
  // matches the corresponding forward action, so callers can parse the same
  // way they did before this batch (string-based grep on `write`, `update`,
  // `upsert`, etc.).
  for (const step of undo) actionLog.push(step.log);
  return { plan, actions: actionLog };
}

export function runUninstall(opts: InstallOptions = {}): InstallResult {
  const plan = buildInstallPlan(opts);
  if (opts.dryRun) {
    const actions: string[] = [];
    printDryRun(plan, false, Boolean(opts.skipMcp));
    return { plan, actions };
  }
  const undo: UndoStep[] = [];
  const actionLog: string[] = [];
  const domain = `gui/${process.getuid?.() ?? os.userInfo().uid}`;
  const runStep = (cmd: string, args: string[], optsR: { ignoreFailure?: boolean } = {}) => {
    actionLog.push([cmd, ...args].map(q).join(' '));
    const r = (opts.spawnSync ?? spawnSync)(cmd, args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
    // ENOENT = binary missing. Tolerated silently when the CLI simply isn't
    // installed (audit D20: missing-CLI is benign, --skip-mcp is the
    // explicit opt-out). Real exec failures still throw so rollback can
    // restore any files runUninstall already removed.
    if (r.error && (r.error as NodeJS.ErrnoException).code === 'ENOENT') return;
    // r.status !== 0 catches BOTH non-zero exit AND spawn errors (EACCES,
    // EPERM, etc.) that leave status = null. ENOENT already silently
    // tolerated above; all other failures must throw so rollback restores
    // files runUninstall already removed (audit D20). r.error.message is the
    // only signal for binaries that failed to launch.
    if (r.status !== 0 && !optsR.ignoreFailure) {
      const detail = ((r.error as Error | undefined)?.message
        ?? (typeof r.stderr === 'string' ? r.stderr : '')
        ?? (typeof r.stdout === 'string' ? r.stdout : '')).trim();
      throw new Error(`${cmd} ${args.join(' ')} failed: ${detail}`);
    }
  };
  try {
    runStep('launchctl', ['bootout', domain, plan.launchAgentPath], { ignoreFailure: true });
    if (fs.existsSync(plan.launchAgentPath)) {
      const prior = readFileOrNull(plan.launchAgentPath);
      fs.rmSync(plan.launchAgentPath);
      actionLog.push(`remove ${plan.launchAgentPath}`);
      undo.push({
        log: `restore ${plan.launchAgentPath}`,
        revert: () => {
          if (prior) {
            try { writeFileAtomic(plan.launchAgentPath, prior, { mode: 0o644 }); } catch { /* best-effort */ }
          }
        },
      });
    }
    if (fs.existsSync(plan.envPath)) {
      const prior = readFileOrNull(plan.envPath);
      fs.rmSync(plan.envPath);
      actionLog.push(`remove ${plan.envPath}`);
      undo.push({
        log: `restore ${plan.envPath}`,
        revert: () => {
          if (prior) {
            try { writeFileAtomic(plan.envPath, prior, { mode: 0o644 }); } catch { /* best-effort */ }
          }
        },
      });
    }
    updateZshrc(plan, undo, false);
    if (!opts.skipMcp) {
      // Audit D20: MCP removal failures must roll back any state already
      // mutated in this try block (e.g. launchd plist removed above). The
      // ENOENT silent path inside runStep still tolerates a missing CLI,
      // so an operator without claude/codex installed can still uninstall.
      runStep('claude', ['mcp', 'remove', '--scope', 'user', MCP_SERVER_NAME]);
      runStep('codex', ['mcp', 'remove', MCP_SERVER_NAME]);
      updateOpencodeConfig(plan, undo, false);
    }
  } catch (err) {
    rollback(undo, err);
  }
  for (const step of undo) actionLog.push(step.log);
  return { plan, actions: actionLog };
}

function status(name: string, ok: boolean, pass: string, fail: string): DoctorCheck {
  return { name, status: ok ? 'pass' : 'fail', detail: ok ? pass : fail };
}

function spawnCheck(name: string, cmd: string, args: string[], deps: DoctorDeps): DoctorCheck {
  const sp = deps.spawnSync ?? spawnSync;
  const r = sp(cmd, args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
  if (r.error && (r.error as NodeJS.ErrnoException).code === 'ENOENT') {
    return { name, status: 'warn', detail: `${cmd} not found` };
  }
  if (r.status === 0) return { name, status: 'pass', detail: `${cmd} ${args.join(' ')}` };
  const msg = String(r.stderr || r.stdout || '').trim();
  return { name, status: 'fail', detail: msg || `${cmd} ${args.join(' ')} exited ${r.status}` };
}

async function healthCheck(plan: InstallPlan, deps: DoctorDeps): Promise<DoctorCheck> {
  const f = deps.fetch ?? fetch;
  const ac = new AbortController();
  const timer = setTimeout(() => ac.abort(), 1500);
  try {
    const res = await f(`${plan.baseUrl}/healthz`, { signal: ac.signal });
    return status('healthz', res.ok, `${plan.baseUrl}/healthz`, `HTTP ${res.status} from ${plan.baseUrl}/healthz`);
  } catch (err) {
    return { name: 'healthz', status: 'fail', detail: (err as Error).message };
  } finally {
    clearTimeout(timer);
  }
}

export async function runDoctor(opts: InstallOptions = {}, deps: DoctorDeps = {}): Promise<DoctorResult> {
  const plan = buildInstallPlan(opts);
  const checks: DoctorCheck[] = [];
  checks.push(status('launchd plist', fs.existsSync(plan.launchAgentPath), plan.launchAgentPath, `missing ${plan.launchAgentPath}`));
  checks.push(status('shell env', fs.existsSync(plan.envPath), plan.envPath, `missing ${plan.envPath}`));
  const zshrc = fs.existsSync(plan.zshrcPath) ? fs.readFileSync(plan.zshrcPath, 'utf8') : '';
  checks.push(status('zshrc source block', zshrc.includes(plan.zshrcBlock), plan.zshrcPath, `missing imgtokenx source block in ${plan.zshrcPath}`));
  checks.push(await healthCheck(plan, deps));

  const domain = `gui/${process.getuid?.() ?? os.userInfo().uid}`;
  checks.push(spawnCheck('launchd service', 'launchctl', ['print', `${domain}/${LAUNCHD_LABEL}`], deps));
  if (!opts.skipMcp) {
    checks.push(spawnCheck('Claude MCP', 'claude', ['mcp', 'get', MCP_SERVER_NAME], deps));
    checks.push(spawnCheck('Codex MCP', 'codex', ['mcp', 'get', MCP_SERVER_NAME], deps));
    const cfgPath = path.join(plan.home, '.config', 'opencode', 'opencode.json');
    let opencodeOk = false;
    if (fs.existsSync(cfgPath)) {
      try {
        const cfg = JSON.parse(fs.readFileSync(cfgPath, 'utf8')) as { mcp?: Record<string, unknown> };
        const entry = cfg.mcp?.[MCP_SERVER_NAME] as { command?: unknown } | undefined;
        opencodeOk = Array.isArray(entry?.command)
          && entry.command[0] === plan.nodePath
          && entry.command[1] === plan.cliPath
          && entry.command[2] === 'mcp';
      } catch {
        opencodeOk = false;
      }
    }
    checks.push(status('OpenCode MCP', opencodeOk, cfgPath, `missing ${MCP_SERVER_NAME} in ${cfgPath}`));
  }
  return { plan, checks };
}

export function doctorExitCode(result: DoctorResult): number {
  return result.checks.some((c) => c.status === 'fail') ? 1 : 0;
}

export function formatDoctor(result: DoctorResult): string {
  const mark = { pass: 'PASS', fail: 'FAIL', warn: 'WARN' } satisfies Record<DoctorStatus, string>;
  return result.checks.map((c) => `${mark[c.status]} ${c.name}: ${c.detail}`).join('\n') + '\n';
}

export function parseInstallArgs(argv: string[]): InstallOptions {
  const opts: InstallOptions = {};
  // Index-based loop so `--port VALUE` (space-separated, like `getopt` /
  // `argparse` conventions) can pull the value from the next argv entry,
  // in addition to the existing `--port=VALUE` (`getopt_long` style).
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]!;
    if (a === '--dry-run') opts.dryRun = true;
    else if (a === '--skip-mcp') opts.skipMcp = true;
    else if (a === '--port') {
      const raw = argv[++i];
      if (raw === undefined) throw new Error('--port requires a value');
      opts.port = parsePortValue(raw);
    }
    else if (a.startsWith('--port=')) {
      opts.port = parsePortValue(a.slice('--port='.length));
    }
    else if (a === '-h' || a === '--help') {
      console.log('Usage: imgtokenx install|uninstall|doctor [--dry-run] [--skip-mcp] [--port=47821]');
      process.exit(0);
    } else {
      throw new Error(`unknown install option: ${a}`);
    }
  }
  return opts;
}

function parsePortValue(raw: string): number {
  const port = Number(raw);
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    throw new Error(`invalid --port value: ${raw}`);
  }
  return port;
}
