import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { spawnSync } from 'node:child_process';

export const LAUNCHD_LABEL = 'com.pxpipe.proxy';
export const MCP_SERVER_NAME = 'pxpipe-recover';

export interface InstallPlan {
  home: string;
  repoRoot: string;
  nodePath: string;
  cliPath: string;
  port: number;
  baseUrl: string;
  pxpipeDir: string;
  envPath: string;
  zshrcPath: string;
  launchAgentPath: string;
  outLog: string;
  errLog: string;
  plist: string;
  envSh: string;
  zshrcBlock: string;
  mcpCommands: string[];
  opencodeMcp: Record<string, unknown>;
}

interface BuildPlanOptions {
  home?: string;
  repoRoot?: string;
  nodePath?: string;
  port?: number;
}

export interface InstallOptions extends BuildPlanOptions {
  dryRun?: boolean;
  skipMcp?: boolean;
}

export interface InstallResult {
  plan: InstallPlan;
  actions: string[];
}

function q(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

function xml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function shDouble(s: string): string {
  return s.replace(/["\\$`]/g, '\\$&');
}

function timestamp(): string {
  return new Date().toISOString().replace(/[:.]/g, '-');
}

function run(cmd: string, args: string[], actions: string[], opts: { ignoreFailure?: boolean } = {}): void {
  actions.push([cmd, ...args].map(q).join(' '));
  const r = spawnSync(cmd, args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
  if (r.status !== 0 && !opts.ignoreFailure) {
    throw new Error(`${cmd} ${args.join(' ')} failed: ${(r.stderr || r.stdout || '').trim()}`);
  }
}

export function renderLaunchAgentPlist(plan: Pick<InstallPlan, 'nodePath' | 'cliPath' | 'port' | 'outLog' | 'errLog' | 'repoRoot'>): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LAUNCHD_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${xml(plan.nodePath)}</string>
    <string>${xml(plan.cliPath)}</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${xml(plan.repoRoot)}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>HOST</key>
    <string>127.0.0.1</string>
    <key>PORT</key>
    <string>${plan.port}</string>
  </dict>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${xml(plan.outLog)}</string>
  <key>StandardErrorPath</key>
  <string>${xml(plan.errLog)}</string>
</dict>
</plist>
`;
}

export function renderShellEnv(plan: Pick<InstallPlan, 'nodePath' | 'cliPath' | 'baseUrl' | 'port'>): string {
  return `# Generated by pxpipe install. Source from ~/.zshrc.
export PXPIPE_BASE_URL="\${PXPIPE_BASE_URL:-${shDouble(plan.baseUrl)}}"
export PXPIPE_PORT="\${PXPIPE_PORT:-${plan.port}}"
export PXPIPE_NODE="\${PXPIPE_NODE:-${shDouble(plan.nodePath)}}"
export PXPIPE_CLI="\${PXPIPE_CLI:-${shDouble(plan.cliPath)}}"

pxpipe_health() {
  command curl -fsS "$PXPIPE_BASE_URL/healthz" >/dev/null 2>&1
}

pxpipe_ensure_proxy() {
  pxpipe_health && return 0
  if command -v launchctl >/dev/null 2>&1; then
    command launchctl kickstart -k "gui/$(id -u)/${LAUNCHD_LABEL}" >/dev/null 2>&1 || true
    sleep 0.3
    pxpipe_health && return 0
  fi
  mkdir -p "$HOME/.pxpipe"
  HOST=127.0.0.1 PORT="$PXPIPE_PORT" nohup "$PXPIPE_NODE" "$PXPIPE_CLI" >> "$HOME/.pxpipe/proxy.out.log" 2>> "$HOME/.pxpipe/proxy.err.log" &
  sleep 0.5
  pxpipe_health
}

claude() {
  if [ "\${PXPIPE_DISABLE:-}" = "1" ]; then command claude "$@"; return $?; fi
  pxpipe_ensure_proxy || echo "[pxpipe] warning: proxy health check failed; running claude anyway" >&2
  ANTHROPIC_BASE_URL="$PXPIPE_BASE_URL" command claude "$@"
}

codex() {
  if [ "\${PXPIPE_DISABLE:-}" = "1" ]; then command codex "$@"; return $?; fi
  pxpipe_ensure_proxy || echo "[pxpipe] warning: proxy health check failed; running codex anyway" >&2
  OPENAI_BASE_URL="$PXPIPE_BASE_URL/v1" command codex "$@"
}

opencode() {
  if [ "\${PXPIPE_DISABLE:-}" = "1" ]; then command opencode "$@"; return $?; fi
  pxpipe_ensure_proxy || echo "[pxpipe] warning: proxy health check failed; running opencode anyway" >&2
  ANTHROPIC_BASE_URL="$PXPIPE_BASE_URL/anthropic" OPENAI_BASE_URL="$PXPIPE_BASE_URL/openai" command opencode "$@"
}
`;
}

function zshrcBlock(envPath: string): string {
  return [
    '# >>> pxpipe auto-start >>>',
    `[ -r ${q(envPath)} ] && . ${q(envPath)}`,
    '# <<< pxpipe auto-start <<<',
  ].join('\n');
}

export function applyZshrcInstall(current: string, block: string): string {
  if (current.includes(block)) return current;
  const withoutOld = applyZshrcUninstall(current);
  return `${withoutOld.replace(/\s*$/, '')}\n\n${block}\n`;
}

export function applyZshrcUninstall(current: string): string {
  return current
    .replace(/\n?# >>> pxpipe auto-start >>>\n[\s\S]*?\n# <<< pxpipe auto-start <<<\n?/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .replace(/^\n+/, '')
    .replace(/\n{2,}$/, '\n');
}

export function buildInstallPlan(opts: BuildPlanOptions = {}): InstallPlan {
  const home = opts.home ?? os.homedir();
  const repoRoot = opts.repoRoot ?? process.cwd();
  const nodePath = opts.nodePath ?? process.execPath;
  const cliPath = path.join(repoRoot, 'bin', 'cli.js');
  const port = opts.port ?? 47821;
  const pxpipeDir = path.join(home, '.pxpipe');
  const launchAgentPath = path.join(home, 'Library', 'LaunchAgents', `${LAUNCHD_LABEL}.plist`);
  const plan = {
    home,
    repoRoot,
    nodePath,
    cliPath,
    port,
    baseUrl: `http://127.0.0.1:${port}`,
    pxpipeDir,
    envPath: path.join(pxpipeDir, 'env.sh'),
    zshrcPath: path.join(home, '.zshrc'),
    launchAgentPath,
    outLog: path.join(pxpipeDir, 'proxy.out.log'),
    errLog: path.join(pxpipeDir, 'proxy.err.log'),
  } as InstallPlan;
  plan.plist = renderLaunchAgentPlist(plan);
  plan.envSh = renderShellEnv(plan);
  plan.zshrcBlock = zshrcBlock(plan.envPath);
  plan.mcpCommands = [
    `claude mcp add --scope user ${MCP_SERVER_NAME} -- ${q(nodePath)} ${q(cliPath)} mcp`,
    `codex mcp add ${MCP_SERVER_NAME} -- ${q(nodePath)} ${q(cliPath)} mcp`,
  ];
  plan.opencodeMcp = {
    enabled: true,
    type: 'local',
    command: [nodePath, cliPath, 'mcp'],
  };
  return plan;
}

function writeIfChanged(file: string, content: string, actions: string[], mode?: number): void {
  if (fs.existsSync(file) && fs.readFileSync(file, 'utf8') === content) return;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content, { mode });
  actions.push(`write ${file}`);
}

function backup(file: string, actions: string[]): void {
  if (!fs.existsSync(file)) return;
  const to = `${file}.bak.${timestamp()}`;
  fs.copyFileSync(file, to);
  actions.push(`backup ${file} -> ${to}`);
}

function updateZshrc(plan: InstallPlan, actions: string[], installing: boolean): void {
  const cur = fs.existsSync(plan.zshrcPath) ? fs.readFileSync(plan.zshrcPath, 'utf8') : '';
  const next = installing ? applyZshrcInstall(cur, plan.zshrcBlock) : applyZshrcUninstall(cur);
  if (next === cur) return;
  backup(plan.zshrcPath, actions);
  fs.writeFileSync(plan.zshrcPath, next);
  actions.push(`${installing ? 'update' : 'clean'} ${plan.zshrcPath}`);
}

function updateOpencodeConfig(plan: InstallPlan, actions: string[], installing: boolean): void {
  const file = path.join(plan.home, '.config', 'opencode', 'opencode.json');
  let cfg: Record<string, unknown> = {};
  if (fs.existsSync(file)) cfg = JSON.parse(fs.readFileSync(file, 'utf8')) as Record<string, unknown>;
  const mcp = (cfg.mcp && typeof cfg.mcp === 'object' && !Array.isArray(cfg.mcp))
    ? { ...(cfg.mcp as Record<string, unknown>) }
    : {};
  if (installing) mcp[MCP_SERVER_NAME] = plan.opencodeMcp;
  else delete mcp[MCP_SERVER_NAME];
  cfg.mcp = mcp;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  backup(file, actions);
  fs.writeFileSync(file, JSON.stringify(cfg, null, 2) + '\n');
  actions.push(`${installing ? 'upsert' : 'remove'} ${MCP_SERVER_NAME} in ${file}`);
}

function printDryRun(plan: InstallPlan, installing: boolean, skipMcp: boolean): void {
  const title = installing ? 'install' : 'uninstall';
  console.log(`[pxpipe ${title}] dry run; no files or live config changed`);
  console.log(`launchd plist: ${plan.launchAgentPath}`);
  console.log(`shell env:     ${plan.envPath}`);
  console.log(`zshrc block:\n${plan.zshrcBlock}`);
  if (installing) {
    console.log(`\nlaunchd plist preview:\n${plan.plist}`);
    console.log(`env.sh preview:\n${plan.envSh}`);
  }
  if (!skipMcp) {
    console.log('\nMCP registration:');
    for (const cmd of plan.mcpCommands) console.log(`  ${cmd}`);
    console.log(`  opencode config mcp.${MCP_SERVER_NAME}: ${JSON.stringify(plan.opencodeMcp)}`);
  }
}

export function runInstall(opts: InstallOptions = {}): InstallResult {
  const plan = buildInstallPlan(opts);
  const actions: string[] = [];
  if (opts.dryRun) {
    printDryRun(plan, true, Boolean(opts.skipMcp));
    return { plan, actions };
  }
  writeIfChanged(plan.launchAgentPath, plan.plist, actions, 0o644);
  writeIfChanged(plan.envPath, plan.envSh, actions, 0o644);
  updateZshrc(plan, actions, true);
  const domain = `gui/${process.getuid?.() ?? os.userInfo().uid}`;
  run('launchctl', ['bootout', domain, plan.launchAgentPath], actions, { ignoreFailure: true });
  run('launchctl', ['bootstrap', domain, plan.launchAgentPath], actions);
  run('launchctl', ['enable', `${domain}/${LAUNCHD_LABEL}`], actions, { ignoreFailure: true });
  run('launchctl', ['kickstart', '-k', `${domain}/${LAUNCHD_LABEL}`], actions, { ignoreFailure: true });
  if (!opts.skipMcp) {
    run('claude', ['mcp', 'remove', '--scope', 'user', MCP_SERVER_NAME], actions, { ignoreFailure: true });
    run('claude', ['mcp', 'add', '--scope', 'user', MCP_SERVER_NAME, '--', plan.nodePath, plan.cliPath, 'mcp'], actions, { ignoreFailure: true });
    run('codex', ['mcp', 'remove', MCP_SERVER_NAME], actions, { ignoreFailure: true });
    run('codex', ['mcp', 'add', MCP_SERVER_NAME, '--', plan.nodePath, plan.cliPath, 'mcp'], actions, { ignoreFailure: true });
    updateOpencodeConfig(plan, actions, true);
  }
  return { plan, actions };
}

export function runUninstall(opts: InstallOptions = {}): InstallResult {
  const plan = buildInstallPlan(opts);
  const actions: string[] = [];
  if (opts.dryRun) {
    printDryRun(plan, false, Boolean(opts.skipMcp));
    return { plan, actions };
  }
  const domain = `gui/${process.getuid?.() ?? os.userInfo().uid}`;
  run('launchctl', ['bootout', domain, plan.launchAgentPath], actions, { ignoreFailure: true });
  if (fs.existsSync(plan.launchAgentPath)) {
    fs.unlinkSync(plan.launchAgentPath);
    actions.push(`remove ${plan.launchAgentPath}`);
  }
  if (fs.existsSync(plan.envPath)) {
    fs.unlinkSync(plan.envPath);
    actions.push(`remove ${plan.envPath}`);
  }
  updateZshrc(plan, actions, false);
  if (!opts.skipMcp) {
    run('claude', ['mcp', 'remove', '--scope', 'user', MCP_SERVER_NAME], actions, { ignoreFailure: true });
    run('codex', ['mcp', 'remove', MCP_SERVER_NAME], actions, { ignoreFailure: true });
    updateOpencodeConfig(plan, actions, false);
  }
  return { plan, actions };
}

export function parseInstallArgs(argv: string[]): InstallOptions {
  const opts: InstallOptions = {};
  for (const a of argv) {
    if (a === '--dry-run') opts.dryRun = true;
    else if (a === '--skip-mcp') opts.skipMcp = true;
    else if (a.startsWith('--port=')) {
      const port = Number(a.slice('--port='.length));
      if (!Number.isInteger(port) || port < 1 || port > 65535) {
        throw new Error(`invalid --port value: ${a.slice('--port='.length)}`);
      }
      opts.port = port;
    }
    else if (a === '-h' || a === '--help') {
      console.log('Usage: pxpipe install|uninstall [--dry-run] [--skip-mcp] [--port=47821]');
      process.exit(0);
    } else {
      throw new Error(`unknown install option: ${a}`);
    }
  }
  return opts;
}
